import Link from "next/link";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
      >
        <nav>
          <div>
            <Link href={{ pathname: `/products` }}>Products</Link>
          </div>
          <div>
            <Link href={{ pathname: `/comments` }}>Comments</Link>
          </div>
        </nav>
        {children}
      </body>
    </html>
  );
}
